Feature/issue 13- HomeScreen - Update UI
Code4Fun-Group/Movie-App pull request #14
Opened 2021-10-14 08:16 UTC by minh5896

## Prerequisite
- [x] Self-review :monocle_face:
- [x] No Crashes ☠️
---

### Root cause
- //[Feature] HomeScreen/ Update UI #13

### Solution
- // use MVVM

### Impact
- // Home Screen

### Screenshots (Optional)
- // Capture affected screen
![Simulator Screen Shot - iPhone 12 Pro - 2021-10-14 at 11 42 55](https://user-images.githubusercontent.com/83936069/137278811-3d60f4c4-3f92-47e1-b97b-3a523ba3914a.png)
![Simulator Screen Shot - iPhone 12 Pro - 2021-10-14 at 14 41 08](https://user-images.githubusercontent.com/83936069/137279013-44603194-5428-4b94-ba9f-b913eb7d6a56.png)

![Simulator Screen Shot - iPhone 12 Pro - 2021-10-14 at 14 40 56](https://user-images.githubusercontent.com/83936069/137278890-f9f86325-4584-46fb-9e4e-972bb1829936.png)
![Simulator Screen Shot - iPhone 12 Pro - 2021-10-14 at 14 41 02](https://user-images.githubusercontent.com/83936069/137278958-0b41716f-fa3c-4b50-b351-b89f1bc14108.png)

2021-10-15 04:38 UTC, namnh92 requested changes

2021-10-15 04:38 UTC, namnh92 commented on MovieApp/SharedData/GlobalConstants.swift
> +	static let listItemCellCV = "ListItemCellCV"
@minh5896 : Move to Model folder of Home screen

2021-10-15 04:38 UTC, namnh92 commented on MovieApp/SharedData/GlobalConstants.swift
> +}
@minh5896 : Move to Model folder of Home screen

2021-10-15 04:38 UTC, namnh92 commented on MovieApp/Screens/Home/Views/PreviewCell/PreviewCollectionViewCell/PreviewCollectionViewCell.swift
> +	// MARK: - LifeCycle
@minh5896 : Add line space

2021-10-15 04:38 UTC, namnh92 commented on MovieApp/Screens/Home/Views/PreviewCell/PreviewCell.swift
> +	weak var delegate: clickedCell?
```suggestion
	// MARK: - Iboutlets
	@IBOutlet weak var previewCollectionView: UICollectionView!
	
	// MARK: - Variables
	weak var delegate: clickedCell?
```

2021-10-15 04:38 UTC, namnh92 commented on MovieApp/Screens/Home/Views/PreviewCell/PreviewCell.swift
>  	// MARK: - Life cycles
```suggestion
	}
	
	// MARK: - Life cycles
```

2021-10-15 04:38 UTC, namnh92 commented on MovieApp/Screens/Home/Views/PreviewCell/PreviewCell.swift
> +// MARK: - UICollectionViewDataSource
```suggestion
	}
	
	// MARK: - Life cycles
	func configure(preview: [MovieViewModel]) {
		previewData = preview
	}
}

// MARK: - UICollectionViewDataSource
```

2021-10-15 04:38 UTC, namnh92 commented on MovieApp/Screens/Home/Views/ListCell/ListMovieCell.swift
> +	// MARK: - UICollectionViewDataSource
```suggestion
// MARK: - UICollectionViewDataSource
```

2021-10-15 04:38 UTC, namnh92 commented on MovieApp/Screens/Home/Views/ListCell/ListMovieCell.swift
> +	// MARK: - UICollectionViewDelegateFlowLayout
```suggestion
// MARK: - UICollectionViewDelegateFlowLayout
```

2021-10-15 04:38 UTC, namnh92 commented on MovieApp/Screens/Home/Views/PreviewCell/PreviewCell.swift
> +protocol clickedCell: AnyObject {
```suggestion
protocol PreviewCellDelegate: AnyObject {
```

2021-10-15 04:38 UTC, namnh92 commented on MovieApp/Screens/Home/Views/ListCell/ListItemCell/ListItemCellCV.swift
> +class ListItemCellCV: UICollectionViewCell {
```suggestion
class ListItemCell: UICollectionViewCell {
```

@minh5896 : What is CV ? Please define name follow with suffix *Cell*

2021-10-15 04:38 UTC, namnh92 commented on MovieApp/Screens/Home/Views/ListCell/ListItemCell/ListItemCellCV.swift
> +	// MARK: - configure
```suggestion
	// MARK: - IbOutlets
	@IBOutlet private weak var imageListItem: UIImageView!
	
	// MARK: - Life cycles
	override func awakeFromNib() {
		super.awakeFromNib()
		imageListItem.image = UIImage(named: "image 2")
		
	}
	
	// MARK: - configure
```

2021-10-15 04:38 UTC, namnh92 commented on MovieApp/Screens/Home/Views/ListCell/ListItemCell/ListItemCellCV.swift
> +		imageListItem.image = UIImage(named: "image 2")
```suggestion
		imageListItem.image = UIImage(named: "icon_xxx")
```
@minh5896 Please define image named follow prefix *icon_*

2021-10-15 04:38 UTC, namnh92 commented on MovieApp/Screens/Home/Views/ListCell/ListMovieCell.swift
> +	// MARK: - configure
```suggestion
	}
	
	// MARK: - configure
```

2021-10-15 04:38 UTC, namnh92 commented on MovieApp/Screens/Home/Views/ListCell/ListMovieCell.swift
> +	var listData = [MovieViewModel]() {
@minh5896 : Please make it private set.

2021-10-15 04:38 UTC, namnh92 commented on MovieApp/Screens/Home/Views/PreviewCell/PreviewCell.swift
> +	func configure(preview: [MovieViewModel]) {
```suggestion
	func configure(preview: [IMovieViewModel]) {
```

@minh5896 : Don't forget SOLID, replace by interface

2021-10-15 07:20 UTC, minh5896 commented on MovieApp/SharedData/GlobalConstants.swift
> +	static let listItemCellCV = "ListItemCellCV"
fix complete

2021-10-15 07:21 UTC, minh5896 commented on MovieApp/SharedData/GlobalConstants.swift
> +}
fix complete

2021-10-15 07:26 UTC, minh5896 commented on MovieApp/Screens/Home/Views/PreviewCell/PreviewCell.swift
> +	weak var delegate: clickedCell?
fix complete

2021-10-15 07:26 UTC, minh5896 commented on MovieApp/Screens/Home/Views/PreviewCell/PreviewCell.swift
>  	// MARK: - Life cycles
fix complete

2021-10-15 07:27 UTC, minh5896 commented on MovieApp/Screens/Home/Views/PreviewCell/PreviewCell.swift
> +// MARK: - UICollectionViewDataSource
fix complete

2021-10-15 07:33 UTC, minh5896 commented on MovieApp/Screens/Home/Views/ListCell/ListMovieCell.swift
> +	// MARK: - UICollectionViewDataSource
fix complete

2021-10-15 07:33 UTC, minh5896 commented on MovieApp/Screens/Home/Views/ListCell/ListMovieCell.swift
> +	// MARK: - UICollectionViewDelegateFlowLayout
fix complete

2021-10-15 07:33 UTC, minh5896 commented on MovieApp/Screens/Home/Views/PreviewCell/PreviewCell.swift
> +protocol clickedCell: AnyObject {
fix complete

2021-10-15 07:35 UTC, minh5896 commented on MovieApp/Screens/Home/Views/ListCell/ListItemCell/ListItemCellCV.swift
> +class ListItemCellCV: UICollectionViewCell {
fix complêt

2021-10-15 07:36 UTC, minh5896 commented on MovieApp/Screens/Home/Views/ListCell/ListItemCell/ListItemCellCV.swift
> +	// MARK: - configure
fix complete

2021-10-15 07:37 UTC, minh5896 commented on MovieApp/Screens/Home/Views/ListCell/ListItemCell/ListItemCellCV.swift
> +		imageListItem.image = UIImage(named: "image 2")
fix complete

2021-10-15 07:37 UTC, minh5896 commented on MovieApp/Screens/Home/Views/ListCell/ListMovieCell.swift
> +	// MARK: - configure
fix complete

2021-10-15 07:40 UTC, minh5896 commented on MovieApp/Screens/Home/Views/ListCell/ListMovieCell.swift
> +	var listData = [MovieViewModel]() {
fix complete

2021-10-15 09:11 UTC, minh5896 commented on MovieApp/Screens/Home/Views/PreviewCell/PreviewCell.swift
> +	func configure(preview: [MovieViewModel]) {
fix complete

2021-10-16 06:27 UTC, namnh92 commented on MovieApp/Screens/Home/Views/HomeMovieCell/HomeMovieCell.swift
>  	}
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/Code4Fun-Group/Movie-App/blob/6d8da324e91a4d6141b0bbfcfe90b541f3760d2d/MovieApp/Screens/Home/Views/HomeMovieCell/HomeMovieCell.swift#L27"></span>Override methods which only call super can be removed</td>
    </tr>
  </tbody>
</table>

2021-10-16 06:27 UTC, namnh92 commented on MovieApp/Screens/Home/Views/ListCell/ListItemCell/ListItemCell.swift
> +	}
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/Code4Fun-Group/Movie-App/blob/6d8da324e91a4d6141b0bbfcfe90b541f3760d2d/MovieApp/Screens/Home/Views/ListCell/ListItemCell/ListItemCell.swift#L18"></span>Override methods which only call super can be removed</td>
    </tr>
  </tbody>
</table>

2021-10-16 06:27 UTC, namnh92 commented
<!--
  0 Errors
  2 Warnings: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/Code4Fun-Group/Movie-App/blob/6d8da324e91a4d6141b0bbfcfe90b541f3760d2d/MovieApp/Screens/Details/DetailsViewController.swift#L14">MovieApp/Screens/Details/DetailsViewController.swift#L14</a> - Override methods which only call super can be removed</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-10-16 08:46 UTC, namnh92 approved these changes

2021-10-16 08:46 UTC, merged