Feature/issue 15- DownloadScreen - Update UI
Code4Fun-Group/Movie-App pull request #16
Opened 2021-10-20 06:28 UTC by minh5896

## Prerequisite
- [x] Self-review :monocle_face:
- [x] No Crashes ☠️
---

### Root cause
- // update UI 

### Solution
- // update UI

### Impact
- // Download Screen

### Screenshots (Optional)
- // Capture affected screens

![Simulator Screen Shot - iPhone 12 Pro - 2021-10-19 at 17 28 12](https://user-images.githubusercontent.com/83936069/138039996-8a584650-63c3-446b-b9d9-065e45a65438.png)
![Simulator Screen Shot - iPhone 12 Pro - 2021-10-19 at 17 28 42](https://user-images.githubusercontent.com/83936069/138040015-28998d38-ff31-45a3-8794-7cf15256f236.png)

2021-10-20 06:32 UTC, namnh92 commented on MovieApp/Screens/Details/DetailsViewController.swift
>  	}
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/Code4Fun-Group/Movie-App/blob/5674ecfc29f32c9bbaa1d4d78e88396268dceeb4/MovieApp/Screens/Details/DetailsViewController.swift#L14"></span>Override methods which only call super can be removed</td>
    </tr>
  </tbody>
</table>

2021-10-20 06:32 UTC, namnh92 commented on MovieApp/Screens/Home/Models/DownloadCell.swift
> +	}
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/Code4Fun-Group/Movie-App/blob/5674ecfc29f32c9bbaa1d4d78e88396268dceeb4/MovieApp/Screens/Home/Models/DownloadCell.swift#L17"></span>Override methods which only call super can be removed</td>
    </tr>
  </tbody>
</table>

2021-10-20 06:37 UTC, minh5896 commented on MovieApp/Screens/Details/DetailsViewController.swift
>  	}
fix compplete

2021-10-20 06:38 UTC, minh5896 commented on MovieApp/Screens/Home/Models/DownloadCell.swift
> +	}
fix complete

2021-10-25 04:25 UTC, namnh92 requested changes

2021-10-25 04:25 UTC, namnh92 commented on MovieApp/Screens/Download/DownloadViewController.swift
> +		setupTableView()
```suggestion
```
@minh5896 : Move to setupUI()

2021-10-25 04:25 UTC, namnh92 commented on MovieApp/Screens/Download/DownloadViewController.swift
> +		return CGSize(width: collectionView.frame.width / 3, height: collectionView.frame.height / 4 )
@minh5896 : Make constants

2021-10-25 04:25 UTC, namnh92 commented on MovieApp/Screens/Download/DownloadViewController.swift
> +		return 0
@minh5896 : Make constants

2021-10-25 04:25 UTC, namnh92 commented on MovieApp/Screens/Download/DownloadViewController.swift
> +		return 0
@minh5896 : Make constants

2021-10-25 04:25 UTC, namnh92 commented on MovieApp/Screens/Download/ViewModels/DownloadViewModel.swift
> +//			self.viewController?.showError()
@minh5896 : Remove comment
```suggestion
```

2021-10-25 04:25 UTC, namnh92 commented on MovieApp/Screens/Home/Views/ContinueCell/ContinueCell.swift
> +		cell.layer.borderColor = UIColor.white.cgColor
@minh5896 : Move configure layout to Cell

2021-10-25 04:25 UTC, namnh92 commented on MovieApp/Screens/Home/Views/ListCell/ListMovieCell.swift
> +	 weak var delegate: CellDelegate?
```suggestion
	weak var delegate: CellDelegate?
```

2021-10-25 04:25 UTC, namnh92 commented on MovieApp/Screens/Home/Views/ListCell/ListMovieCell.swift
> +		cell.layer.borderColor = UIColor.white.cgColor
@minh5896 : Move configure to Cell

2021-10-25 04:25 UTC, namnh92 commented on MovieApp/Screens/Home/Views/ListCell/ListMovieCell.swift
>  		return 5
@minh5896 : Make constants

2021-10-28 06:21 UTC, minh5896 commented on MovieApp/Screens/Download/DownloadViewController.swift
> +		setupTableView()
fix complete

2021-10-28 06:25 UTC, minh5896 commented on MovieApp/Screens/Download/DownloadViewController.swift
> +		return CGSize(width: collectionView.frame.width / 3, height: collectionView.frame.height / 4 )
fix complete

2021-10-28 06:25 UTC, minh5896 commented on MovieApp/Screens/Download/DownloadViewController.swift
> +		return 0
fix complete

2021-10-28 06:26 UTC, minh5896 commented on MovieApp/Screens/Download/ViewModels/DownloadViewModel.swift
> +//			self.viewController?.showError()
fix complete

2021-10-28 06:26 UTC, minh5896 commented on MovieApp/Screens/Home/Views/ContinueCell/ContinueCell.swift
> +		cell.layer.borderColor = UIColor.white.cgColor
fix complete

2021-10-28 06:27 UTC, minh5896 commented on MovieApp/Screens/Home/Views/ListCell/ListMovieCell.swift
> +		cell.layer.borderColor = UIColor.white.cgColor
fix complete

2021-10-28 06:28 UTC, minh5896 commented on MovieApp/Screens/Home/Views/ListCell/ListMovieCell.swift
>  		return 5
fix complete

2021-10-28 06:31 UTC, minh5896 commented on MovieApp/Screens/Home/Views/ListCell/ListMovieCell.swift
> +	 weak var delegate: CellDelegate?
fix complete

2021-10-28 06:32 UTC, minh5896 commented on MovieApp/Screens/Download/DownloadViewController.swift
> +		return 0
fix complete

2021-10-28 06:34 UTC, namnh92 commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-10-28 07:14 UTC, merged