Feature/issue 17 - MoreScreen - Update UI
Code4Fun-Group/Movie-App pull request #18
Opened 2021-10-22 08:46 UTC by minh5896

## Prerequisite
- [x] Self-review :monocle_face:
- [x] No Crashes ☠️
---

### Root cause
- // Update Ui

### Solution
- // Update UI

### Impact
- //  Screen

### Screenshots (Optional)
- // Capture affected screens
![Simulator Screen Shot - iPhone 12 Pro - 2021-10-22 at 15 11 53](https://user-images.githubusercontent.com/83936069/138423453-7a52f166-81d7-4625-9b3e-52f33b3d6411.png)

2021-10-22 09:45 UTC, namnh92 requested changes

2021-10-22 09:45 UTC, namnh92 commented on MovieApp/Screens/Download/DownloadViewController.swift
> +		return cell
```suggestion
```
@minh5896 : Move to Cell, not configure in View Controller

2021-10-22 09:45 UTC, namnh92 commented on MovieApp/Screens/Download/DownloadViewController.swift
> +		return CGSize(width: collectionView.frame.width / 3, height: collectionView.frame.height / 4 )
@minh5896 : Make constants, do not define magic number 3, 4 ...

2021-10-22 09:45 UTC, namnh92 commented on MovieApp/Screens/Download/DownloadViewController.swift
> +		return 0
@minh5896 : Make constants, do not define magic number

2021-10-22 09:45 UTC, namnh92 commented on MovieApp/Screens/Download/DownloadViewController.swift
> +		return 0
@minh5896 : Make constants, do not define magic number

2021-10-22 09:45 UTC, namnh92 commented on MovieApp/Screens/Download/ViewModels/DownloadViewModel.swift
> +//			self.viewController?.showError()
@minh5896 : Remove comment

2021-10-22 09:45 UTC, namnh92 commented on MovieApp/Screens/Home/HomeViewController.swift
> +}
@
```suggestion

```
@minh5896 Move to Model

2021-10-22 09:45 UTC, namnh92 commented on MovieApp/Screens/Download/ViewModels/ProfileTableViewCell.swift
> +		cell.layer.borderColor = UIColor.white.cgColor
```suggestion

```
@minh5896 Move to Cell, not configure in View Controller

2021-10-22 10:17 UTC, minh5896 commented on MovieApp/Screens/Home/HomeViewController.swift
> +}
fix complete

2021-10-22 10:22 UTC, minh5896 commented on MovieApp/Screens/Download/DownloadViewController.swift
> +		return cell
fix complete

2021-10-22 10:22 UTC, minh5896 commented on MovieApp/Screens/Download/DownloadViewController.swift
> +		return 0
fix complete

2021-10-22 10:22 UTC, minh5896 commented on MovieApp/Screens/Download/ViewModels/DownloadViewModel.swift
> +//			self.viewController?.showError()
fix complete

2021-10-22 10:22 UTC, minh5896 commented on MovieApp/Screens/Download/DownloadViewController.swift
> +		return 0
fix complete

2021-10-22 10:23 UTC, minh5896 commented on MovieApp/Screens/Download/DownloadViewController.swift
> +		return CGSize(width: collectionView.frame.width / 3, height: collectionView.frame.height / 4 )
fix complete

2021-10-22 12:28 UTC, namnh92 commented on MovieApp/Screens/Download/ViewModels/StandardTableViewCell.swift
> +}
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/Code4Fun-Group/Movie-App/blob/ce9aed5811734fd696fc2fb4d8ff634e8118eb8e/MovieApp/Screens/Download/ViewModels/StandardTableViewCell.swift#L18"></span>Override methods which only call super can be removed</td>
    </tr>
  </tbody>
</table>

2021-10-22 12:28 UTC, namnh92 commented on MovieApp/Screens/Home/Views/TVShowCell/TvShowViewCell.swift
>  	}
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/Code4Fun-Group/Movie-App/blob/e147228c034589666db4398fcda9585015f8903c/MovieApp/Screens/Home/Views/TVShowCell/TvShowViewCell.swift#L21"></span>Override methods which only call super can be removed</td>
    </tr>
  </tbody>
</table>

2021-10-22 12:28 UTC, namnh92 commented on MovieApp/Screens/More/Views/MyListCell/MyListTableViewCell.swift
> +}
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/Code4Fun-Group/Movie-App/blob/e147228c034589666db4398fcda9585015f8903c/MovieApp/Screens/More/Views/MyListCell/MyListTableViewCell.swift#L19"></span>Override methods which only call super can be removed</td>
    </tr>
  </tbody>
</table>

2021-10-22 12:28 UTC, namnh92 commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-10-25 00:28 UTC, minh5896 commented on MovieApp/Screens/Download/ViewModels/StandardTableViewCell.swift
> +}
fix complete

2021-10-25 00:29 UTC, minh5896 commented on MovieApp/Screens/Home/Views/TVShowCell/TvShowViewCell.swift
>  	}
fix complete

2021-10-25 00:31 UTC, minh5896 commented on MovieApp/Screens/More/Views/MyListCell/MyListTableViewCell.swift
> +}
fix complete

2021-10-29 11:04 UTC, closed without merging