Issue 24
Code4Fun-Group/Movie-App pull request #25
Opened 2021-11-09 09:29 UTC by dong2810

## Prerequisite
- [ ] Self-review :monocle_face:
- [ ] No Crashes ☠️
---

### Root cause
- // Explain what you have done

### Solution
- // Explain how you fix it

### Impact
- // List of affected components/modules

### Screenshots (Optional)
- // Capture affected screens

2021-11-09 09:37 UTC, dong2810 commented
complete screen search

2021-11-10 10:40 UTC, namnh92 requested changes

2021-11-10 10:40 UTC, namnh92 commented on MovieApp/Networking/MovieAppResourceResponseAdapter.swift
> +
```suggestion
```

2021-11-10 10:40 UTC, namnh92 commented on MovieApp/Screens/Search/SearchViewController.swift
> +
```suggestion

```

2021-11-10 10:40 UTC, namnh92 commented on MovieApp/Screens/Search/SearchViewController.swift
> +		searchCollectionView.register(UINib(nibName: ConstantSearch.searchCollectionReusableView, bundle: Bundle.main), forSupplementaryViewOfKind: UICollectionView.elementKindSectionHeader, withReuseIdent
Separate to sub function

2021-11-10 10:40 UTC, namnh92 commented on MovieApp/Screens/Search/SearchViewController.swift
> +		navigationItem.hidesSearchBarWhenScrolling = false
Separate to sub function

2021-11-10 10:40 UTC, namnh92 commented on MovieApp/Screens/Search/SearchViewController.swift
> +extension SearchViewController: UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
Separate each extension only has one protocol

2021-11-10 10:40 UTC, namnh92 commented on MovieApp/Screens/Search/SearchViewController.swift
> +		return CGSize(width: collectionView.frame.width, height: collectionView.frame.height / 6)
Make constants, don't use magic number *6*

2021-11-10 10:40 UTC, namnh92 commented on MovieApp/Screens/Search/SearchViewController.swift
> +		return CGSize(width: view.frame.size.width, height: view.frame.size.width / 10)
Make constants, don't use magic number 10

2021-11-10 10:40 UTC, namnh92 commented on MovieApp/Screens/Search/Views/SearchMovieCell/SearchDetailCell.swift
> +//		searchName.textColor = .white
Remove comment

2021-11-10 10:42 UTC, namnh92 commented
Please create PR follow rule:
1. Name
2. Description

2021-11-10 11:16 UTC, dong2810 commented on MovieApp/Screens/Search/SearchViewController.swift
> +		navigationItem.hidesSearchBarWhenScrolling = false
fixed

2021-11-10 14:30 UTC, merged